#!/bin/sh

ssldir=/var/lib/puppet/ssl
fqdn=`hostname -f`

if [ -f $ssldir/certs/$fqdn.pem -a -f $ssldir/private_keys/$fqdn.pem ]; then
    sed -e "s|\(ssl_certificate.*$ssldir/[a-z_]*\).*|\1/$fqdn.pem;|" \
        -i /etc/nginx.conf
else
    echo Could not find puppetmaster\'s certificate or private key. Re-trying...
    sleep 10
    exit 1
fi

exec s6-setuidgid puppet \
    nginx -g "daemon off;" -c /etc/nginx.conf
